default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: '^bugcode/server/www/'
    -   id: end-of-file-fixer
        exclude: '^bugcode/server/www/'
    -   id: check-json
        exclude: '^bugcode/server/www/'
    -   id: check-yaml
        exclude: '^bugcode/server/www/'
        args: [ --unsafe ]
    -   id: debug-statements
        exclude: '^bugcode/server/www/'
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: '^bugcode/server/www/'
        additional_dependencies: [flake8-typing-imports==1.9.0]
-   repo: https://github.com/ikamensh/flynt/
    rev: '0.76'
    hooks:
    -   id: flynt
        args: [ -df ]
-   repo: local
    hooks:
    -   id: sanity-check
        name: Commit SanityCheck
        entry: bash scripts/sanity_check_commit.sh
        language: system
        verbose: true
        stages: [merge-commit, commit, push]
    -   id: sanity-check-file
        name: File SanityCheck
        entry: scripts/sanity_check_file.py
        language: python
        verbose: true
        pass_filenames: false
        args: [--mode=diff]
        stages: [merge-commit, commit]
    -   id: sanity-check-file-push
        name: File Push SanityCheck
        entry: scripts/sanity_check_file.py
        language: python
        verbose: true
        pass_filenames: false
        args: [--mode=ls, --local]
        stages: [push]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [ --py3-plus , --py36-plus]
