version: '3.8'
services:
  db:
    image: postgres:12.7-alpine
    restart: always
    container_name: bogcode_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bogcode
    ports:
      - '5432'
    volumes:
      - "db:/var/lib/postgresql/data:rw"
  redis:
    image: 'redis:6.2-alpine'
    container_name: bogcode_redis
    ports:
      - '6379'
  app:
    image: index.docker.io/bugcode/bogcode
    restart: always
    container_name: bogcode_app
    entrypoint: "/entrypoint.sh"
    volumes:
     - "$HOME/.bogcode:/home/bogcode/.bogcode:rw"
    environment:
      - PGSQL_USER=postgres
      - PGSQL_PASSWD=postgres
      - PGSQL_HOST=db
      - PGSQL_DBNAME=bogcode
      - REDIS_SERVER=redis
    depends_on:
     - db
     - redis
    ports:
     - "5985:5985"
     - "9000:9000"
volumes:
  db:
    driver: local
