publish_pypi:
    image: python:3.11
    stage: publish
    script:
      - !reference [ .get_from_tar_and_replace_www, script ]
      - apt-get update -qy
      - apt-get install twine -y
      - python setup.py sdist bdist_wheel
      - twine upload -u $PYPI_USER -p $PYPI_PASS dist/* --verbose
    rules:
      - !reference [ .on-community-tag, rules ]
    needs:
      - project: khulnasoft/bugcode-react
        job: npm_build
        ref: community/master
        artifacts: true
