test_hypothesis:
    tags:
        - hypothesis
    image: nixos/nix:2.16.0
    stage: test
    allow_failure: true
    script:
        - nix-env -if pynixify/nixpkgs.nix -A vault
        - !reference [ .get_secrets, script ]
        - nix-env -if pynixify/nixpkgs.nix -A cachix
        - mkdir -p ~/.config/cachix
        - export USER=$(whoami)
        - echo "$CACHIX_CONFG" >~/.config/cachix/cachix.dhall
        - cachix use bugcode
        - "echo 'hosts: files dns' >/etc/nsswitch.conf"
        - export LC_ALL=C.UTF-8
        - export LANG=C.UTF-8
        - mkdir -p ~/.bogcode/config
        - cp tests/data/server.ini ~/.bogcode/config
        - mkdir run_from
        - nix-shell --command "pytest tests -v --cov=bogcode/server/api --disable-warnings --connection-string=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB -m hypothesis"
    rules:
      - if: $HYPO_TEST
        when: on_success
      - !reference [.pipeline-control-test, rules]
      - when: never
