#agent_integration_and_db_regression:
#    stage: post_testing
#    variables:
#      BUGCODE_REF: $CI_COMMIT_REF_NAME
#      BUGCODE_REGRESSION: "True"
#    trigger:
#      project: bugcode/devops
#      strategy: depend
#    rules:
#      - if: '$CI_COMMIT_REF_NAME =~ /^.*\/(master)$/'
#        variables:
#          DISPATCHER_REF: master
#        when: on_success
#      - if: '$CI_COMMIT_REF_NAME =~ /^.*\/(staging)$/'
#        variables:
#          DISPATCHER_REF: staging
#        when: on_success
#      - if: '$INTEGRATION || $FULL_TEST || $DAILY_TEST'
#        variables:
#          DISPATCHER_REF: staging
#        when: on_success
#      - when: never
