.unit_tests_base:
    tags:
        - bogcodetests
    stage: test
    coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
    script:
        - export LC_ALL=C.UTF-8
        - export LANG=C.UTF-8
        - mkdir -p ~/.bogcode/config
        - cp tests/data/server.ini ~/.bogcode/config
        - mkdir run_from
        - source bogcode_venv/bin/activate
        - cd run_from && pytest ../tests -v --capture=sys --cov=../bogcode/server --color=yes --disable-warnings --connection-string=postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB
    needs: [] # Speed up tests
    artifacts:
        when: on_failure
        paths:
            - ~/.bogcode/logs/bogcode-server.log

.latest_unit_test_base:
  extends: .unit_tests_base
  before_script:
      - pip install virtualenv
      - virtualenv bogcode_venv
      - source bogcode_venv/bin/activate
      - pip install .
      - pip install -r requirements_dev.txt
      - pip install pytest-cov
      - pip install pyyaml
  after_script:
      - source bogcode_venv/bin/activate
      - pip freeze
  allow_failure: true
  rules:
      # - !reference [ .pipeline-control-test, rules ]
      # - !reference [ .dev-staging-master, rules ]
      - if: '$ALPHA_TEST'
        when: on_success
      - when: never


.alpha_unit_test_base:
  extends: .unit_tests_base
  before_script:
      - pip install virtualenv
      - virtualenv bogcode_venv
      - source bogcode_venv/bin/activate
      - pip install --pre .
      - pip install --pre -r requirements_dev.txt
      - pip install --pre pytest-cov
      - pip install --pre pyyaml
  after_script:
    - source bogcode_venv/bin/activate
    - pip freeze
  allow_failure: true
  rules:
      # - !reference [ .pipeline-control-test, rules ]
      # - !reference [ .dev-staging-master, rules ]
      - if: '$ALPHA_TEST'
        when: on_success
      - when: never

unit_test 3.7:
    extends: .latest_unit_test_base
    image: python:3.7

unit_test 3.8:
    extends: .latest_unit_test_base
    image: python:3.8

unit_test 3.9:
    extends: .latest_unit_test_base
    image: python:3.9

unit_test 3.10:
    extends: .latest_unit_test_base
    image: python:3.10

alpha_unit_test 3.7:
    extends: .alpha_unit_test_base
    image: python:3.7

alpha_unit_test 3.8:
    extends: .alpha_unit_test_base
    image: python:3.8
    rules:
        # - !reference [ .pipeline-control-test, rules ]
        # - !reference [ .dev-staging-master, rules ]
        - if: '$ALPHA_TEST'
          when: on_success
        - when: never

alpha_unit_test 3.9:
    extends: .alpha_unit_test_base
    image: python:3.9


alpha_unit_test 3.10:
    extends: .alpha_unit_test_base
    image: python:3.10
