smoke_test_deb:
    allow_failure: false
    stage: build_testing  # TODO improve
    image: ubuntu:18.04
    needs:
      - job: generate_deb_dev
        artifacts: true
    script:
        - apt-get update -y
        - apt install -y sudo curl
        - apt-get install -y ./bugcode-server_amd64.deb
        - which bugcode-manage
        - bugcode-manage show-urls
        - export BUGCODE_HOME=/home/bugcode
        - /opt/bugcode/bin/bugcode-server || true  # create .bugcode
        - "echo '[database]' >>~bugcode/.bugcode/config/server.ini"
        - echo "connection_string = postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres/$POSTGRES_DB" >>~bugcode/.bugcode/config/server.ini
        - cat ~bugcode/.bugcode/config/server.ini
        - bugcode-manage create-tables
        - /opt/bugcode/bin/bugcode-server &
        - sleep 5
        - curl -v http://localhost:5985/_api/v2/info
        - kill $(cat ~bugcode/.khulnasoft/bugcode-server-port-5985.pid)
        - jobs
    rules:
        - !reference [.be-uploaded, rules]
        # What is not '/staging' is '/dev', '/master' or a development branch , and all are manual
        - !reference [.ignore-on-staging, rules]
        - !reference [.ignore-on-master, rules]
        - when: never
